include:
  - pihole-unbound/compose.yaml
  - stirling/compose.yaml
  - traefik/compose.yaml
  - miniflux/compose.yaml
  - mazanoke/compose.yaml
  - readeck/compose.yaml
  - beszel/compose.yaml
  - backrest/compose.yaml
