include:
  - pihole-unbound/compose.yaml
  - traefik/compose.yaml
  - miniflux/compose.yaml
  - mazanoke/compose.yaml
  - readeck/compose.yaml
  - beszel/compose.yaml
  - bentopdf/compose.yaml
  - pocket-id/compose.yaml
