services:
  bentopdf:
    image: bentopdf/bentopdf:${BENTOPDF_VERSION}
    container_name: bentopdf
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bentopdf.rule=Host(`bentopdf.${BASE_URL}`)"
      - "traefik.http.services.bentopdf.loadbalancer.server.port=8080"

networks:
  homelab:
    external: true
