services:
  backrest:
    image: garethgeorge/backrest:${BACKREST_VERSION}
    container_name: backrest
    volumes:
      - /srv/docker/backrest/data:/data
      - /srv/docker/backrest/config:/config
      - /srv/docker/backrest/cache:/cache
      - /srv/docker/backrest/tmp:/tmp
      - /srv/backups:/userdata
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backrest.rule=Host(`backrest.${BASE_URL}`)"
      - "traefik.http.services.backrest.loadbalancer.server.port=9898"