services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.15.4
    volumes:
      - /srv/docker/beszel:/beszel-data
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.home`)"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"

networks:
  homelab:
    external: true
