services:
  beszel:
    image: henrygd/beszel:${BESZEL_VERSION}
    container_name: beszel
    restart: unless-stopped
    mem_limit: 256m
    mem_reservation: 64m
    cpus: 0.25
    volumes:
      - /srv/docker/beszel:/beszel_data
      - /srv/docker/beszel/socket:/beszel_socket
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.${BASE_URL}`)"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      start_period: 5s
      interval: 120s

  beszel-agent:
    image: henrygd/beszel-agent:${BESZEL_VERSION}
    container_name: beszel-agent
    restart: unless-stopped
    mem_limit: 128m
    mem_reservation: 32m
    cpus: 0.1
    networks:
      - homelab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/docker/beszel-agent:/var/lib/beszel-agent
      - /srv/docker/beszel/socket-agent:/beszel_socket
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      HUB_URL: http://beszel:8090
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s

networks:
  homelab:
    external: true
